name: auaraiy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  flutter_spinkit: 5.1.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
  flutter_screenutil: ^5.6.1
  intl: 0.17.0
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
  weather: ^2.0.1
  flutter_weather_bg_null_safety: ^1.0.0
  json_path: 0.4.1
  latlng: ^0.2.0
  local_auth: ^2.1.5
  local_auth_android: ^1.0.19
  local_auth_ios: ^1.0.13
  local_auth_windows: ^1.0.6
  page_transition: 2.0.4
  provider: 6.0.4
  shared_preferences: ^2.0.18
  timeago: 3.2.2
  url_launcher: 6.1.5
  cupertino_icons: ^1.0.0
  bloc: ^8.1.1
  weather_icons: ^3.0.0
  open_weather_client: ^2.1.0
  equatable: ^2.0.5
  dio: ^5.0.1
  flutter_bloc: ^8.1.2
  rive: ^0.10.2
  flutter_network_connectivity: ^0.0.6
  connectivity_plus: ^3.0.3
  

dev_dependencies:

  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/rive/
  fonts:
    - family: 'Gilroy_kz'
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Extrabold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900